### ISSUE TITLE
Extension-Icons are not accessible

### ISSUE THREAD

**Issue by maximilian-walter** [helhum/typo3-secure-web#8]
The extension-icons in the root-directory of a extension (eg typo3conf/ext/example/ext_icon.gif) are not accessible anymore, because they are not linked in the public-directory.

Is this the intended behaviour? In my opinion all icon-files(ext_icon.{gif,png,svg}) should also be linked to prevent many broken images in the backend (eg in the extension-manager).

Thanks!

**Comment by helhum** [comment]
Hi and thanks for your report!

Since TYPO3 8.7 extensions can provide their icon as [Resources/Public/Icons/Extension.png](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/about/Resources/Public/Icons/Extension.png)

Like any other public asset extensions provide, also the ext icon must be put below `Resources/Public` to be fully compatible with the approach this package offers.

**Comment by maximilian-walter** [comment]
Thanks for your feedback! I didn't realize that the ext_icon-files are deprecated.

If others have the same problem: I added the following Composer-scripts as a workaround (replace "flux vhs" with the list of affected extensions):

```json
"scripts": {
    "post-autoload-dump": [
        "for ext in flux vhs; do mkdir -p public/typo3conf/ext/${ext} && (cd public/typo3conf/ext/${ext} && rm -f ext_icon.* && ln -s ../../../../private/typo3conf/ext/${ext}/ext_icon.*); done"
    ]
}
```
